name: 刷步数

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 3 13 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: 开始
        run: |
          pip3 install requests
          user1='${{ secrets.USER }}'
          passwd1='${{ secrets.PWD }}'
          skey='${{ secrets.SKEY }}'
          sckey='${{ secrets.SCKEY }}'
          position='${{ secrets.POSITION }}'
          corpid='${{ secrets.CORPID }}'
          corpsecret='${{ secrets.CORPSECRET }}'
          agentid='${{ secrets.AGENTID }}'
          touser='${{ secrets.TOUSER }}'
          toparty='${{ secrets.TOPARTY }}'
          totag='${{ secrets.TOTAG }}'
          open_get_weather='${{ secrets.OPEN_GET_WEATHER }}'
          area='${{ secrets.AREA }}'
          python3 main.py ${user1} ${passwd1} ${skey} ${sckey} ${position} ${corpid} ${corpsecret} ${agentid} ${touser} ${toparty} ${totag} ${open_get_weather} ${area}

      - name: 重置刷新时间
        run: |
          zsh random_cron.sh
          git_pwd='${{ secrets.GIT_PWD }}'
          git config --global user.name "xunichanghuan"
          git config --global user.email "zhpjake@vip.qq.com"
          git add .
          git commit -m '重置下次刷新时间'
          git remote set-url origin http://xunichanghuan:${git_pwd}@github.com/xunichanghuan/mimotion.git
          git push
